#!/usr/bin/env node
// Amendment 11: creates the ed25519 key pair that signs shared-folder update manifests.
// The private key is written OUTSIDE the repository; the public key goes into
// shared/update-public-key.mjs, which is committed and shipped with the app.
import { generateKeyPairSync } from "node:crypto";
import { mkdir, stat, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";

export const DEFAULT_PRIVATE_KEY_PATH = path.join(os.homedir(), ".automate-taskboard", "update-ed25519.pem");
const projectRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

function isInside(child, parent) {
  const relative = path.relative(path.resolve(parent), path.resolve(child));
  return relative === "" || (!relative.startsWith("..") && !path.isAbsolute(relative));
}

export function publicKeyModuleSource(publicKeyPem) {
  return `// Amendment 11: ed25519 public key that verifies shared-folder update manifests.
// Generated by scripts/update-keygen.mjs; the private key is kept outside the repository.
export const UPDATE_PUBLIC_KEY_PEM = ${JSON.stringify(publicKeyPem)};
`;
}

export async function generateUpdateKeys({
  privateKeyPath = DEFAULT_PRIVATE_KEY_PATH,
  publicModulePath = path.join(projectRoot, "shared", "update-public-key.mjs"),
  repositoryRoot = projectRoot,
  force = false,
} = {}) {
  if (isInside(privateKeyPath, repositoryRoot)) {
    throw new Error(`Refusing to write the private key inside the repository: ${privateKeyPath}`);
  }
  if (!force) {
    const existing = await stat(privateKeyPath).then(() => true, () => false);
    if (existing) throw new Error(`Private key already exists (use --force to replace): ${privateKeyPath}`);
  }
  const { publicKey, privateKey } = generateKeyPairSync("ed25519");
  const privatePem = privateKey.export({ type: "pkcs8", format: "pem" });
  const publicPem = publicKey.export({ type: "spki", format: "pem" });
  await mkdir(path.dirname(privateKeyPath), { recursive: true });
  await writeFile(privateKeyPath, privatePem, { mode: 0o600 });
  await writeFile(publicModulePath, publicKeyModuleSource(publicPem));
  return { privateKeyPath, publicModulePath, publicKeyPem: publicPem };
}

async function main(argv) {
  const options = { force: false };
  for (let index = 0; index < argv.length; index += 1) {
    const argument = argv[index];
    if (argument === "--force") options.force = true;
    else if (argument === "--private-key") options.privateKeyPath = argv[++index];
    else if (argument === "--public-module") options.publicModulePath = argv[++index];
    else throw new Error(`Unknown option: ${argument}`);
  }
  const result = await generateUpdateKeys(options);
  console.log(JSON.stringify({ privateKeyPath: result.privateKeyPath, publicModulePath: result.publicModulePath }, null, 2));
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  main(process.argv.slice(2)).catch((error) => {
    console.error(error.message);
    process.exit(1);
  });
}
